name: CI

env:
  PROJECT_NAME: PointCloudSegmentation
  
on:
  push:
    branches:
      - github_workflow
    
jobs:
  
  codeStyle:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
        
      - name: autopep8
        uses: peter-evans/autopep8@v1.2.0
     
  
  CI:
    needs: [codeStyle]
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker version
        run: docker -v
     
