name: CI

env:
  PROJECT_NAME: PointCloudSegmentation
  
on:
  push:
    branches:
      - github_workflow
    
jobs:
  
  codeStyle:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: action/checkout@v2
        
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.14.0
     
  
  CI:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker version
        run: docker -v
     
